name: Rapport de bug
description: Signaler un bug
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Merci de remplir ce formulaire pour signaler un bug.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description claire et concise du bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Étapes pour reproduire
      description: Comment reproduire le bug ?
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '...'
        3. Voir l'erreur
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer ?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environnement
      placeholder: |
        - iOS : 18.0
        - Xcode : 16.0
        - Device : iPhone 16 Simulator
    validations:
      required: false